// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// 
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcBEZ1i6Jnj8fdyIzTPZjYAT0cZNQo5qw',
    appId: '1:703394418503:web:3dc1f0a6dc8f643e214662',
    messagingSenderId: '703394418503',
    projectId: 'paypocket-804a2',
    authDomain: 'paypocket-804a2.firebaseapp.com',
    storageBucket: 'paypocket-804a2.firebasestorage.app',
    measurementId: 'G-GS2JFSVYXS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7tItAP2QE44G4vtGFQZDlX4V_RRAG5uo',
    appId: '1:703394418503:android:ad6a4cf5a64b5d7e214662',
    messagingSenderId: '703394418503',
    projectId: 'paypocket-804a2',
    storageBucket: 'paypocket-804a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNzc_3KKbYnkIovxtixi5FVbhKhTRQVdc',
    appId: '1:703394418503:ios:8d11568f04e4ceee214662',
    messagingSenderId: '703394418503',
    projectId: 'paypocket-804a2',
    storageBucket: 'paypocket-804a2.firebasestorage.app',
    iosBundleId: 'com.paypocket.payPocket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNzc_3KKbYnkIovxtixi5FVbhKhTRQVdc',
    appId: '1:703394418503:ios:8d11568f04e4ceee214662',
    messagingSenderId: '703394418503',
    projectId: 'paypocket-804a2',
    storageBucket: 'paypocket-804a2.firebasestorage.app',
    iosBundleId: 'com.paypocket.payPocket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcBEZ1i6Jnj8fdyIzTPZjYAT0cZNQo5qw',
    appId: '1:703394418503:web:38c691f08fcb2dc5214662',
    messagingSenderId: '703394418503',
    projectId: 'paypocket-804a2',
    authDomain: 'paypocket-804a2.firebaseapp.com',
    storageBucket: 'paypocket-804a2.firebasestorage.app',
    measurementId: 'G-EXGX5QG4N0',
  );

}